http:
  port: 8080
  logs: true
logger:
  level: debug
  pretty: true
storage:
  endpoint: https://oos.eu-west-2.outscale.com
  bucket: git
  region: eu-west-2
  access-key-id: zzxxxx
  secret-key-id: zzzzxxxxx